This challenge consists of two sets of files:

* `X.CSV` for various values of `X`: contains data similar to what you were to produce for the C++ part of this challenge. Specifically, each file contains the average, min, max, and standard deviation of the total acceleration in 10 second long time windows for a single video. The `start` and `end` columns indicate the bounds of the time window in milliseconds from the beginning of the video.
* `X.jumps.csv` for various values of `X`: these files go with the matching `X.CSV` files and indicate when a kite surfer jumped. That is, if one row of `X.jumps.csv` has `start == 53280` and `end == 55540` then a kite surfer jumped, leaving the water at 53280 milliseconds from the beginning of the video and landing back on the water at 55540 milliseconds from the beginning of the video.

The goal is to be able to predict time windows which contain kite jumps. This Jupyter Notebook is a (bad) attempt at building a model to do that. Your challenge is to identify the various ways this attempt could be improved. You do not need to actual fix the code (though that is permitted). You can simply add new Markdown cells to the notebook indicating the mistakes you observe and suggesting improvements.

In [6]:
import pandas as pd
import numpy as np
import glob
import os.path
from keras.layers import Input, Dense
from keras.models import Model
from keras import optimizers
import sklearn.model_selection as ms

In [7]:
data_dir='challenge_data'

Read all the forces and jump data into dictionaries whose keys are the names of the jump files and whose values are the Pandas DataFrame instances holding the data.

In [8]:
force_files = glob.glob(os.path.join(data_dir, '*.CSV'))
jump_files = glob.glob(os.path.join(data_dir, '*.jumps.csv'))

forces = {}
for ff in force_files:
    forces[ff] = pd.read_csv(ff)
jumps = {}
for ff, jf in zip(force_files, jump_files):
    # Use the forces filename as the key so we can easily match the jump times with
    # the corresponding forces
    jumps[ff] = pd.read_csv(jf)

In [9]:
forces.keys()

['challenge_data/V3.CSV',
 'challenge_data/V4.CSV',
 'challenge_data/V1.CSV',
 'challenge_data/V2.CSV']

In [10]:
forces['challenge_data/V1.CSV'].head()

        avg       max       min  start    stddev    end
0  1.193093  3.077215  0.120284      0  0.568452  10000
1  1.188233  3.077215  0.120284    500  0.572365  10500
2  1.188903  3.077215  0.120284   1000  0.575058  11000
3  1.194125  3.077215  0.120284   1500  0.577237  11500
4  1.221625  3.113024  0.120284   2000  0.595027  12000

In [11]:
jumps.keys()

['challenge_data/V3.CSV',
 'challenge_data/V4.CSV',
 'challenge_data/V1.CSV',
 'challenge_data/V2.CSV']

In [12]:
jumps['challenge_data/V1.CSV'].head()

       Start        End
0   295800.0   298000.0
1   379600.0   384300.0
2   558300.0   562800.0
3  1056300.0  1060700.0
4  1125400.0  1129500.0

Now we want to join the computed data (the summary statistics for each time window) against the jumps data so we have a target for supervised learning. Specifically, if the window for a row contains a jump then our target is `True`. Otherwise it is `False`.

In [13]:
for k in forces.keys():
    cur_f = forces[k]
    cur_f['Target'] = False
    jt = jumps[k]
    for i in range(jt.shape[0]):
        start = jt.Start.iloc[i]
        end = jt.End.iloc[i]
        cur_f.loc[(cur_f.start <= start) & (cur_f.end >= end), 'Target'] = True

In [14]:
jumps['challenge_data/V1.CSV'].head()

       Start        End
0   295800.0   298000.0
1   379600.0   384300.0
2   558300.0   562800.0
3  1056300.0  1060700.0
4  1125400.0  1129500.0

In [15]:
# Make sure we set our target correctly
f1 = forces['challenge_data/V1.CSV']
f1[(f1.start > 280000) & (f1.start < 310000)]

          avg       max       min   start    stddev     end  Target
561  1.038614  1.619985  0.668307  280500  0.140928  290500   False
562  1.051160  1.619985  0.668307  281000  0.139471  291000   False
563  1.049243  1.619985  0.668307  281500  0.136830  291500   False
564  1.040384  1.619985  0.668307  282000  0.133006  292000   False
565  1.047557  1.619985  0.668307  282500  0.143634  292500   False
566  1.050927  1.619985  0.668307  283000  0.145682  293000   False
567  1.047278  1.619985  0.668307  283500  0.139229  293500   False
568  1.052787  1.588935  0.668307  284000  0.133720  294000   False
569  1.047150  1.588935  0.800859  284500  0.130529  294500   False
570  1.045195  1.588935  0.749637  285000  0.134458  295000   False
571  1.043844  1.588935  0.749637  285500  0.133035  295500   False
572  1.048790  1.588935  0.749637  286000  0.134492  296000   False
573  1.049587  1.588935  0.749637  286500  0.136924  296500   False
574  1.043882  1.588935  0.749637  287000  0.137025  297000   False
575  1.045775  1.588935  0.749637  287500  0.138931  297500   False
576  1.043233  1.588935  0.749637  288000  0.136528  298000    True
577  1.034264  1.588935  0.749637  288500  0.134597  298500    True
578  1.029124  1.588935  0.749637  289000  0.136045  299000    True
579  1.028870  1.588935  0.749637  289500  0.136415  299500    True
580  1.032343  1.588935  0.749637  290000  0.136587  300000    True
581  1.033655  1.588935  0.749637  290500  0.136564  300500    True
582  1.025161  1.588935  0.749637  291000  0.132333  301000    True
583  1.025054  1.588935  0.749637  291500  0.134403  301500    True
584  1.024296  1.588935  0.749637  292000  0.134700  302000    True
585  1.023482  1.353410  0.749637  292500  0.120904  302500    True
586  1.017455  1.353410  0.749637  293000  0.118612  303000    True
587  1.017692  1.353410  0.749637  293500  0.117935  303500    True
588  1.013856  1.330936  0.749637  294000  0.111948  304000    True
589  1.017775  1.330936  0.749637  294500  0.109071  304500    True
590  1.016285  1.330936  0.798860  295000  0.100988  305000    True
591  1.012325  1.330936  0.798860  295500  0.103443  305500    True
592  1.016896  1.471998  0.798860  296000  0.105565  306000   False
593  1.016358  1.471998  0.798860  296500  0.103025  306500   False
594  1.028750  1.584322  0.798860  297000  0.117228  307000   False
595  1.026432  1.584322  0.798860  297500  0.116964  307500   False
596  1.024948  1.584322  0.798860  298000  0.117514  308000   False
597  1.024183  1.584322  0.798860  298500  0.117055  308500   False
598  1.028356  1.584322  0.798860  299000  0.115892  309000   False
599  1.026937  1.584322  0.798860  299500  0.114799  309500   False
600  1.026981  1.584322  0.798860  300000  0.113305  310000   False
601  1.029829  1.584322  0.798860  300500  0.113480  310500   False
602  1.030069  1.584322  0.798860  301000  0.111644  311000   False
603  1.018462  1.584322  0.729193  301500  0.114901  311500   False
604  1.017565  1.584322  0.729193  302000  0.114755  312000   False
605  1.024826  1.584322  0.729193  302500  0.122250  312500   False
606  1.034050  1.584322  0.729193  303000  0.125685  313000   False
607  1.031682  1.584322  0.729193  303500  0.131404  313500   False
608  1.032393  1.584322  0.729193  304000  0.140254  314000   False
609  1.036177  1.584322  0.729193  304500  0.143739  314500   False
610  1.048944  1.584322  0.729193  305000  0.156937  315000   False
611  1.054153  1.584322  0.729193  305500  0.156108  315500   False
612  1.052811  1.584322  0.729193  306000  0.160919  316000   False
613  1.055745  1.584322  0.729193  306500  0.161463  316500   False
614  1.049339  1.558542  0.729193  307000  0.153721  317000   False
615  1.051036  1.706796  0.729193  307500  0.158329  317500   False
616  1.062239  1.847063  0.729193  308000  0.178333  318000   False
617  1.067474  1.847063  0.729193  308500  0.184537  318500   False
618  1.074408  1.847063  0.729193  309000  0.195524  319000   False
619  1.077842  1.847063  0.729193  309500  0.196235  319500   False

In [16]:
# Now concatenate things into one big data set
all_data = pd.concat(forces.values(), ignore_index=True)

Don't keep any data separate for an actual test set which is independent of both the training and validation.

In [17]:
all_data.head()

        avg       max       min  start    stddev    end  Target
0  0.979240  1.434954  0.654423      0  0.061798  10000   False
1  0.978753  1.434954  0.654423    500  0.060129  10500   False
2  0.976366  1.434954  0.654423   1000  0.059742  11000   False
3  0.976729  1.434954  0.654423   1500  0.053761  11500   False
4  0.975602  1.434954  0.479002   2000  0.060523  12000   False

In [18]:
all_data.shape

(8397, 7)

In [19]:
sum([x.shape[0] for x in forces.values()])

8397

Now split the data into training and test data sets.

In [20]:
train, valid = ms.train_test_split(all_data, test_size=0.2)

In [21]:
train.head()

           avg       max       min    start    stddev      end  Target
4574  1.286037  4.157926  0.119931   748000  0.593629   758000   False
1101  1.616383  6.503060  0.358433   550500  0.835429   560500   False
5958  1.040207  1.457351  0.804496   445000  0.111250   455000   False
2459  1.636622  6.260625  0.370994  1229500  0.924980  1239500   False
458   1.460342  3.744293  0.405085   229000  0.544053   239000   False

In [22]:
valid.head()

           avg       max       min   start    stddev     end  Target
453   1.466148  3.508835  0.405085  226500  0.527799  236500   False
1249  1.996287  4.575622  0.236244  624500  0.922710  634500   False
6975  1.376434  4.062463  0.406345  198000  0.648803  208000   False
8166  1.269831  3.446483  0.404536  793500  0.523956  803500   False
1949  1.427231  7.853846  0.470511  974500  0.776878  984500   False

In [23]:
train.shape

(6717, 7)

In [24]:
valid.shape

(1680, 7)

Now lets see if we can train a neural network on this data.

In [25]:
inputs = Input(shape=(4,))
l1 = Dense(10, activation='sigmoid')(inputs)
l2 = Dense(15, activation='sigmoid')(l1)
out = Dense(1, activation='sigmoid')(l2)
model = Model(inputs=inputs, outputs=out)

In [26]:
def to_data_and_target(df):
    """Given either our training or test data set return a pair of (data, targets) where data is just the
    columns that should be input and targets are just the corresponding targets."""
    data = df[['avg', 'min', 'max', 'stddev']]
    targets = df.Target
    return (data, targets)

In [27]:
train_d, train_t = to_data_and_target(train)

In [28]:
train_d.head()

           avg       min       max    stddev
4574  1.286037  0.119931  4.157926  0.593629
1101  1.616383  0.358433  6.503060  0.835429
5958  1.040207  0.804496  1.457351  0.111250
2459  1.636622  0.370994  6.260625  0.924980
458   1.460342  0.405085  3.744293  0.544053

In [29]:
train_t.head()

4574    False
1101    False
5958    False
2459    False
458     False
Name: Target, dtype: bool

The model is trained on data that has not been normalized. Since there is a large difference in the magnitudes of the variables (ie max is always much greater than min), then it is likely that these variables may be unjustly weighted through training.

In [31]:
opt = optimizers.SGD(lr=0.02, momentum=0.2, decay=1e-6)
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])
model.fit(x=train_d.values, y=train_t.values, epochs=50, verbose=2)

Epoch 1/50
 - 1s - loss: 0.1635 - acc: 0.9614
Epoch 2/50
 - 1s - loss: 0.1635 - acc: 0.9614
Epoch 3/50
 - 1s - loss: 0.1635 - acc: 0.9614
Epoch 4/50
 - 1s - loss: 0.1635 - acc: 0.9614
Epoch 5/50
 - 1s - loss: 0.1635 - acc: 0.9614
Epoch 6/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 7/50
 - 1s - loss: 0.1635 - acc: 0.9614
Epoch 8/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 9/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 10/50
 - 1s - loss: 0.1635 - acc: 0.9614
Epoch 11/50
 - 1s - loss: 0.1635 - acc: 0.9614
Epoch 12/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 13/50
 - 1s - loss: 0.1635 - acc: 0.9614
Epoch 14/50
 - 1s - loss: 0.1635 - acc: 0.9614
Epoch 15/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 16/50
 - 1s - loss: 0.1635 - acc: 0.9614
Epoch 17/50
 - 1s - loss: 0.1635 - acc: 0.9614
Epoch 18/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 19/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 20/50
 - 1s - loss: 0.1635 - acc: 0.9614
Epoch 21/50
 - 1s - loss: 0.1635 - acc: 0.9614
Epoch 22/50
 - 1s - loss: 0.1635 - acc: 0.9614
Epoch 23/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 24/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 25/50
 - 1s - loss: 0.1635 - acc: 0.9614
Epoch 26/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 27/50
 - 1s - loss: 0.1635 - acc: 0.9614
Epoch 28/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 29/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 30/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 31/50
 - 1s - loss: 0.1635 - acc: 0.9614
Epoch 32/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 33/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 34/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 35/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 36/50
 - 1s - loss: 0.1633 - acc: 0.9614
Epoch 37/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 38/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 39/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 40/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 41/50
 - 1s - loss: 0.1635 - acc: 0.9614
Epoch 42/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 43/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 44/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 45/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 46/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 47/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 48/50
 - 1s - loss: 0.1635 - acc: 0.9614
Epoch 49/50
 - 1s - loss: 0.1634 - acc: 0.9614
Epoch 50/50
 - 1s - loss: 0.1634 - acc: 0.9614

There is no early stopping, creating the potential for overfitting.

In [32]:
valid_d, valid_t = to_data_and_target(valid)
model.evaluate(valid_d.values, valid_t.values)

1680/1680 [==============================] - 0s 132us/step

[0.15801479589371453, 0.96309523809523812]

It looks like things were still improving after 50 epoch so maybe we should try more.

In [ ]:
opt = optimizers.SGD(lr=0.02, momentum=0.2, decay=1e-6)
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])
model.fit(x=train_d.values, y=train_t.values, epochs=100, verbose=2)

In [ ]:
valid_d, valid_t = to_data_and_target(valid)
model.evaluate(valid_d.values, valid_t.values)

And it looks like even after 100 epochs things were still improving, though slowly. So maybe we should try more and/or increase the learning rate and/or decrease the decay. Let's try something like that.

In [ ]:
opt = optimizers.SGD(lr=0.04, momentum=0.2, decay=1e-7)
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])
model.fit(x=train_d.values, y=train_t.values, epochs=200, verbose=2)

That looks pretty good! Let's assess accuracy on our validation data set.

In [ ]:
valid_d, valid_t = to_data_and_target(valid)
model.evaluate(valid_d.values, valid_t.values)

Awesome! Better than 95% accuracy our validation set. This is a good model!

This accuracy is actually very unimpressive, since there is a serious class imbalance that the model has incredibly low outputs for both jumps and non-jumps as seen below. Therefore, this high accuracy is actually just due to the class imbalance already present.

In [33]:

print(model.predict(valid_d))

[[ 0.03806587]
 [ 0.0366641 ]
 [ 0.03794405]
 ...,
 [ 0.03821696]
 [ 0.03717816]
 [ 0.03700233]]

Should measure the accuracy of the model on each class (jump and non-jump) before deeming it a good model.

Likely this model is too simple and requires more data to train on, more features, and more parameters to possibly find a good fit. Since these are strict requirements, a neural network is likely not ideal and other methods that are not as susceptible to class imbalances should be chosen, most likely a random forest.